# Import Libraries

In [1]:
# Alter data.
import pandas as pan
# OS interactions.
import os
# Print screen alternative. 
from IPython.display import display

# Read CSV

In [7]:
# Get working directory
cwd_loc = os.getcwd()
print("Working directory:\t" + cwd_loc, "\n")

data_filename = "data-raw.csv"
data_file_exist = False
cwd_filenames = list()
with os.scandir(cwd_loc + "/data") as directory:
    for element in directory:
        if element.is_file():
            cwd_filenames.append(element.name)
            print(f"Name:\t\t\t{element.name}\nPath:\t\t\t{element.path}")

            # Read file if file name found in directory.
            if element.name == data_filename:
                data_file_exist = True
                crime_data = pan.read_csv(element.path)

print(f"\nCrime data file exist:\t{data_file_exist}")

Working directory:	/home/rolarrin/projects/crime-sql-pandas-pyspark

Name:			data-raw.csv
Path:			/home/rolarrin/projects/crime-sql-pandas-pyspark/data/data-raw.csv
Name:			data-clean-pandas.csv
Path:			/home/rolarrin/projects/crime-sql-pandas-pyspark/data/data-clean-pandas.csv

Crime data file exist:	True

# Data

In [8]:
# First 5 records
crime_data.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

# Data Information
## *Data Structure*

In [184]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005104 entries, 0 to 1005103
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1005104 non-null  int64
 1   Date Rptd       1005104 non-null  object
 2   DATE OCC        1005104 non-null  object
 3   TIME OCC        1005104 non-null  int64
 4   AREA            1005104 non-null  int64
 5   AREA NAME       1005104 non-null  object
 6   Rpt Dist No     1005104 non-null  int64
 7   Part 1-2        1005104 non-null  int64
 8   Crm Cd          1005104 non-null  int64
 9   Crm Cd Desc     1005104 non-null  object
 10  Mocodes         853380 non-null   object
 11  Vict Age        1005104 non-null  int64
 12  Vict Sex        860353 non-null   object
 13  Vict Descent    860341 non-null   object
 14  Premis Cd       1005088 non-null  float64
 15  Premis Desc     1004516 non-null  object
 16  Weapon Used Cd  327244 non-null   float64
 17  Weapon Desc     327244 non-null   object
 18  Status          1005103 non-null  object
 19  Status Desc     1005104 non-null  object
 20  Crm Cd 1        1005093 non-null  float64
 21  Crm Cd 2        69146 non-null    float64
 22  Crm Cd 3        2315 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1005104 non-null  object
 25  Cross Street    154237 non-null   object
 26  LAT             1005104 non-null  float64
 27  LON             1005104 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 214.7+ MB

# Checklist
### 1. *Delete redundant columns.*
### 2. *Renaming the columns.*
### 3. *Drop duplicates.*
### 4. *Remove null values.*
### 5. *Clean each column.*
### 6. *Check for additional transformations.*
### 7. *Save new data.*

### 1. *Delete redundant coloumns.*

In [ ]:
# Record count
crime_data_length = len(crime_data)
print('Records #:\t' + str(crime_data_length))

Records #:	1005104

In [ ]:
columns_to_drop = ['Vict Descent', 'Weapon Used Cd', 'Status']
crime_data_drop = crime_data.drop(columns = columns_to_drop)

print('Orginal crime data length:\t' + str(crime_data.shape[0]))
print('Orginal crime data width:\t' + str(crime_data.shape[1]))
print('Columns dropped:\t\t' + str(len(columns_to_drop)))
print('Test crime data length:\t\t' + str(crime_data_drop.shape[0]))
print('Test crime data width:\t\t' + str(crime_data_drop.shape[1]))

Orginal crime data length:	1005104
Orginal crime data width:	28
Columns dropped:		3
Test crime data length:		1005104
Test crime data width:		25

### 2. *Renaming the columns.*
- Remove spaces.
- Remove dashes.
- Add underscores.

In [ ]:
def line_break(dash_count=40):
    print('\n', '-' * dash_count, '\n')

# New capitalized column names without dashes or spaces
new_column_names = []
print("**NEW COLUMN NAMES**")
for name in crime_data_drop.columns:
    print(name.replace(' ','_').replace('-','_').upper())
    new_column_names.append(name.replace(' ','_').replace('-','_').upper())

crime_data_rename = crime_data_drop.copy() 
crime_data_rename.columns = new_column_names

line_break()
equity = False
if set(new_column_names) == set(crime_data_rename.columns):
    equity = True
print("Column names change: {}".format(equity))

line_break()
crime_data_rename.info()

**NEW COLUMN NAMES**
DR_NO
DATE_RPTD
DATE_OCC
TIME_OCC
AREA
AREA_NAME
RPT_DIST_NO
PART_1_2
CRM_CD
CRM_CD_DESC
MOCODES
VICT_AGE
VICT_SEX
PREMIS_CD
PREMIS_DESC
WEAPON_DESC
STATUS_DESC
CRM_CD_1
CRM_CD_2
CRM_CD_3
CRM_CD_4
LOCATION
CROSS_STREET
LAT
LON

 ----------------------------------------

Column names change: True

 ----------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005104 entries, 0 to 1005103
Data columns (total 25 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   DR_NO         1005104 non-null  int64
 1   DATE_RPTD     1005104 non-null  object
 2   DATE_OCC      1005104 non-null  object
 3   TIME_OCC      1005104 non-null  int64
 4   AREA          1005104 non-null  int64
 5   AREA_NAME     1005104 non-null  object
 6   RPT_DIST_NO   1005104 non-null  int64
 7   PART_1_2      1005104 non-null  int64
 8   CRM_CD        1005104 non-null  int64
 9   CRM_CD_DESC   1005104 non-null  object
 10  MOCODES       853380 non-null   object
 11  VICT_AGE      1005104 non-null  int64
 12  VICT_SEX      860353 non-null   object
 13  PREMIS_CD     1005088 non-null  float64
 14  PREMIS_DESC   1004516 non-null  object
 15  WEAPON_DESC   327244 non-null   object
 16  STATUS_DESC   1005104 non-null  object
 17  CRM_CD_1      1005093 non-null  float64
 18  CRM_CD_2      69146 non-null    float64
 19  CRM_CD_3      2315 non-null     float64
 20  CRM_CD_4      64 non-null       float64
 21  LOCATION      1005104 non-null  object
 22  CROSS_STREET  154237 non-null   object
 23  LAT           1005104 non-null  float64
 24  LON           1005104 non-null  float64
dtypes: float64(7), int64(7), object(11)
memory usage: 191.7+ MB

In [ ]:
crime_data_rename.head()

,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,CRM_CD_DESC,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,NaN,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,NaN,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,NaN,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,NaN,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

### 3. *Drop duplicates.*

In [ ]:
# Check duplicate values
print(crime_data_rename.duplicated().value_counts())

line_break()
duplicate_values = False
if crime_data_rename.duplicated().sum() > 1:
    duplicate_values = True
print(f'Duplicate value(s) exist: {str(duplicate_values)}')

False    1005104
Name: count, dtype: int64

 ----------------------------------------

Duplicate value(s) exist: False

In [ ]:
crime_data_rename

,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,CRM_CD_DESC,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,NaN,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,NaN,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,NaN,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,NaN,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005099,250304184,02/18/2025 12:00:00 AM,02/14/2025 12:00:00 AM,1200,3,Southwest,328,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,700 W 28TH ST,NaN,34.0270,-118.2794
1005100,252104053,01/19/2025 12:00:00 AM,01/17/2025 12:00:00 AM,1530,21,Topanga,2114,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,NaN,Invest Cont,341.0,NaN,NaN,NaN,22200 ELKWOOD ST,NaN,34.2128,-118.6103
1005101,250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,Southwest,358,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895
1005102,250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,Southwest,325,1,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",...,NaN,Invest Cont,522.0,NaN,NaN,NaN,2600 ELLENDALE PL,NaN,34.0307,-118.2923
1005103,250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,Harbor,509,1,210,ROBBERY,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,210.0,NaN,NaN,NaN,24300 WESTERN AV,NaN,33.8046,-118.3074

### 4. *Remove null values.*

In [ ]:
crime_data_rename.isna()

,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,CRM_CD_DESC,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,True,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005099,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
1005100,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
1005101,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
1005102,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,False,True,False,False
1005103,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,True,False,False

In [ ]:
print("Records #:\t{}".format(str(crime_data_length)))

line_break()
print("**NULL COUNT PER COLUMN**")
print(crime_data_rename.isna().sum())

line_break()
note = """Not dropping any further columns. 
Only optional columns contain large number of null values."""
print(note)

Records #:	1005104

 ----------------------------------------

**NULL COUNT PER COLUMN**
DR_NO                 0
DATE_RPTD             0
DATE_OCC              0
TIME_OCC              0
AREA                  0
AREA_NAME             0
RPT_DIST_NO           0
PART_1_2              0
CRM_CD                0
CRM_CD_DESC           0
MOCODES          151724
VICT_AGE              0
VICT_SEX         144751
PREMIS_CD            16
PREMIS_DESC         588
WEAPON_DESC      677860
STATUS_DESC           0
CRM_CD_1             11
CRM_CD_2         935958
CRM_CD_3        1002789
CRM_CD_4        1005040
LOCATION              0
CROSS_STREET     850867
LAT                   0
LON                   0
dtype: int64

 ----------------------------------------

Not dropping any further columns.
Only optional columns contain large number of null values.

### 5. *Clean each column.*
- Capitalize string fields.
- Reset index.
- Convert applicable float fields to integer.

In [ ]:
crime_data_rename

,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,CRM_CD_DESC,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,NaN,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,NaN,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,NaN,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,NaN,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005099,250304184,02/18/2025 12:00:00 AM,02/14/2025 12:00:00 AM,1200,3,Southwest,328,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,700 W 28TH ST,NaN,34.0270,-118.2794
1005100,252104053,01/19/2025 12:00:00 AM,01/17/2025 12:00:00 AM,1530,21,Topanga,2114,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,NaN,Invest Cont,341.0,NaN,NaN,NaN,22200 ELKWOOD ST,NaN,34.2128,-118.6103
1005101,250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,Southwest,358,1,510,VEHICLE - STOLEN,...,NaN,Invest Cont,510.0,NaN,NaN,NaN,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895
1005102,250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,Southwest,325,1,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",...,NaN,Invest Cont,522.0,NaN,NaN,NaN,2600 ELLENDALE PL,NaN,34.0307,-118.2923
1005103,250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,Harbor,509,1,210,ROBBERY,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,210.0,NaN,NaN,NaN,24300 WESTERN AV,NaN,33.8046,-118.3074

In [ ]:
# Capitalize string fields
columns_lowercased = ["CRM_CD_DESC", "STATUS_DESC", "AREA_NAME"]
for column in columns_lowercased:
    crime_data_rename[column] = crime_data_rename[column].str.upper()
    display(crime_data_rename[column])
    line_break()

0                                           VEHICLE - STOLEN
1                                      BURGLARY FROM VEHICLE
2                                              BIKE - STOLEN
3                   SHOPLIFTING-GRAND THEFT ($950.01 & OVER)
4                                           VEHICLE - STOLEN
                                 ...
1005099                                     VEHICLE - STOLEN
1005100    THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...
1005101                                     VEHICLE - STOLEN
1005102    VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...
1005103                                              ROBBERY
Name: CRM_CD_DESC, Length: 1005104, dtype: object

 ----------------------------------------

0          ADULT ARREST
1           INVEST CONT
2           INVEST CONT
3           INVEST CONT
4           INVEST CONT
               ...
1005099     INVEST CONT
1005100     INVEST CONT
1005101     INVEST CONT
1005102     INVEST CONT
1005103     INVEST CONT
Name: STATUS_DESC, Length: 1005104, dtype: object

 ----------------------------------------

0            WILSHIRE
1             CENTRAL
2           SOUTHWEST
3            VAN NUYS
4          HOLLENBECK
              ...
1005099     SOUTHWEST
1005100       TOPANGA
1005101     SOUTHWEST
1005102     SOUTHWEST
1005103        HARBOR
Name: AREA_NAME, Length: 1005104, dtype: object

 ----------------------------------------

In [ ]:
crime_data_rename.reset_index(inplace = True)
crime_data_rename

,index,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,WILSHIRE,784,1,510,...,NaN,ADULT ARREST,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,CENTRAL,182,1,330,...,NaN,INVEST CONT,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,SOUTHWEST,356,1,480,...,NaN,INVEST CONT,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,VAN NUYS,964,1,343,...,NaN,INVEST CONT,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,HOLLENBECK,413,1,510,...,NaN,INVEST CONT,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005099,1005099,250304184,02/18/2025 12:00:00 AM,02/14/2025 12:00:00 AM,1200,3,SOUTHWEST,328,1,510,...,NaN,INVEST CONT,510.0,NaN,NaN,NaN,700 W 28TH ST,NaN,34.0270,-118.2794
1005100,1005100,252104053,01/19/2025 12:00:00 AM,01/17/2025 12:00:00 AM,1530,21,TOPANGA,2114,1,341,...,NaN,INVEST CONT,341.0,NaN,NaN,NaN,22200 ELKWOOD ST,NaN,34.2128,-118.6103
1005101,1005101,250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,SOUTHWEST,358,1,510,...,NaN,INVEST CONT,510.0,NaN,NaN,NaN,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895
1005102,1005102,250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,SOUTHWEST,325,1,522,...,NaN,INVEST CONT,522.0,NaN,NaN,NaN,2600 ELLENDALE PL,NaN,34.0307,-118.2923
1005103,1005103,250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,HARBOR,509,1,210,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",INVEST CONT,210.0,NaN,NaN,NaN,24300 WESTERN AV,NaN,33.8046,-118.3074

In [ ]:
columns_float = list()
print("**FLOAT COLUMNS**")
for column in crime_data_rename.columns:
    if "float" in str(crime_data_rename.dtypes[column]):
        print(column)
        columns_float.append(column)

line_break()
for column in columns_float:
    display(column, crime_data_rename[column].unique())
    line_break()

columns_keep_as_float = ["LON", "LAT"]
columns_to_int = [item for item in columns_float if item not in columns_keep_as_float]
print("**FLOAT TO INT COLUMNS**")
print(columns_to_int)

**FLOAT COLUMNS**
PREMIS_CD
CRM_CD_1
CRM_CD_2
CRM_CD_3
CRM_CD_4
LAT
LON

 ----------------------------------------

'PREMIS_CD'

array([101., 128., 502., 405., 221., 201., 203., 108., 103., 301., 247.,
       501., 507., 210., 102., 510., 402., 725., 104., 401., 121., 122.,
       707., 123., 220., 119., 403., 801., 906., 710., 231., 124., 726.,
       517., 708., 235., 242., 903., 702., 406., 232., 503., 253., 504.,
       116., 949., 720., 735., 252., 750., 721., 118., 254., 218., 505.,
       156., 109., 518., 222., 208., 704., 834., 945., 214., 729., 713.,
       753., 243., 249., 514., 251., 835., 508., 114., 418., 701., 404.,
       511., 158., 904., 415., 516., 722., 755., 229., 152., 717., 145.,
       719., 202., 217., 106., 408., 946., 727., 409., 142., 417., 709.,
       966., 732., 515., 730., 718., 802., 506., 211., 407., 741., 935.,
       738., 413., 138., 120., 744., 416., 206., 244., 900., 146., 248.,
       754., 916., 219., 901., 605., 519., 411., 971., 728., 509., 606.,
       110., 207., 410., 602., 230., 902., 705., 140., 716., 157., 141.,
       948., 723., 603., 213., 303., 736., 908., 117., 154., 205., 712.,
       239., 751., 512., 907., 953., 412., 151., 236., 127., 212., 911.,
       115., 706., 733., 255., 105., 897., 757., 940., 703., 954., 144.,
       752., 238., 302., 910., 742., 148., 919., 237., 934., 111., 149.,
       876., 896., 204., 233., 234., 944., 895., 877., 147., 809., 947.,
       950., 209., 107., 933., 932., 607., 139., 943., 739., 931., 909.,
       256., 216., 112., 970., 974., 804., 724., 915., 962., 937., 228.,
       871., 941., 872., 740., 135., 918., 811., 608., 250., 968., 513.,
       963., 952., 414., 601., 893., 875., 227., 215., 917., 874., 969.,
        nan, 225., 936., 890., 746., 714., 892., 967., 961., 150., 246.,
       125., 810., 891., 223., 113., 898., 224., 715., 245., 604., 155.,
       748., 873., 965., 964., 743., 745., 136., 942., 870., 143., 882.,
       868., 913., 921., 241., 885., 922., 912., 905., 956., 920., 957.,
       951., 737., 758., 880., 884., 129., 756., 958., 711., 304., 869.,
       878., 883., 731., 879., 137., 803., 305., 889., 240., 805., 126.,
       734., 894., 836., 972., 973., 976., 975.])

 ----------------------------------------

'CRM_CD_1'

array([510., 330., 480., 343., 648., 310., 805., 806., 946., 745., 626.,
       210., 341., 230., 354., 624., 442., 662., 900., 901., 440., 740.,
       121., 331., 888., 520., 437., 668., 410., 956., 930., 845., 661.,
       420., 237., 761., 320., 753., 623., 522., 820., 850., 450., 627.,
       625., 886., 236., 755., 890., 903., 220., 231., 649., 664., 815.,
       251., 922., 951., 920., 250., 350., 235., 940., 470., 810., 812.,
       860., 822., 813., 651., 122., 434., 647., 762., 932., 910., 110.,
       763., 441., 821., 902., 814., 756., 433., 421., 352., 443., 660.,
       666., 950., 943.,  nan, 439., 933., 345., 928., 351., 670., 652.,
       949., 760., 622., 446., 113., 438., 471., 451., 436., 521., 653.,
       654., 474., 921., 485., 954., 942., 487., 944., 347., 865., 870.,
       473., 880., 475., 444., 435., 906., 931., 349., 353., 430., 452.,
       924., 840., 948., 884., 904., 830., 432., 882., 445., 926., 453.])

 ----------------------------------------

'CRM_CD_2'

array([998.,  nan, 624., 812., 930., 740., 761., 480., 626., 820., 860.,
       745., 521., 946., 648., 910., 901., 230., 999., 821., 990., 980.,
       420., 815., 920., 649., 933., 236., 888., 510., 625., 943., 341.,
       250., 310., 440., 900., 627., 433., 940., 330., 350., 921., 996.,
       753., 850., 903., 813., 664., 434., 442., 520., 451., 670., 666.,
       997., 942., 653., 410., 660., 441., 951., 647., 220., 810., 814.,
       762., 956., 522., 886., 354., 944., 993., 210., 623., 972., 890.,
       331., 431., 902., 445., 251., 654., 668., 343., 928., 473., 763.,
       830., 662., 949., 906., 979., 760., 474., 950., 471., 994., 932.,
       430., 931., 822., 231., 661., 978., 922., 954., 976., 651., 486.,
       948., 352., 421., 320., 945., 755., 351., 345., 235., 437., 865.,
       485., 450., 470., 438., 924., 846.])

 ----------------------------------------

'CRM_CD_3'

array([ nan, 930., 998., 810., 910., 740., 761., 753., 901., 888., 745.,
       946., 820., 990., 626., 933., 860., 997., 815., 993., 999., 902.,
       763., 653., 900., 830., 956., 648., 434., 940., 813., 943., 649.,
       821., 906., 310., 903., 850., 520.])

 ----------------------------------------

'CRM_CD_4'

array([ nan, 998., 930., 821., 910., 999., 946.])

 ----------------------------------------

'LAT'

array([34.0375, 34.0444, 34.021 , ..., 33.7139, 33.8518, 33.7675])

 ----------------------------------------

'LON'

array([-118.3506, -118.2628, -118.3002, ..., -118.6226, -118.6552,
       -118.6323])

 ----------------------------------------

**FLOAT TO INT COLUMNS**
['PREMIS_CD', 'CRM_CD_1', 'CRM_CD_2', 'CRM_CD_3', 'CRM_CD_4']

In [ ]:
# Fill in nulls with '0', convert float to int
for column in columns_to_int:
    crime_data_rename[column] = crime_data_rename[column].fillna(0).astype(int)
    print("Column: {}, Data type: {} ".format(column, crime_data_rename.dtypes[column]))

Column: PREMIS_CD, Data type: int32
Column: CRM_CD_1, Data type: int32
Column: CRM_CD_2, Data type: int32
Column: CRM_CD_3, Data type: int32
Column: CRM_CD_4, Data type: int32

In [ ]:
crime_data_rename.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005104 entries, 0 to 1005103
Data columns (total 26 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   index         1005104 non-null  int64
 1   DR_NO         1005104 non-null  int64
 2   DATE_RPTD     1005104 non-null  object
 3   DATE_OCC      1005104 non-null  object
 4   TIME_OCC      1005104 non-null  int64
 5   AREA          1005104 non-null  int64
 6   AREA_NAME     1005104 non-null  object
 7   RPT_DIST_NO   1005104 non-null  int64
 8   PART_1_2      1005104 non-null  int64
 9   CRM_CD        1005104 non-null  int64
 10  CRM_CD_DESC   1005104 non-null  object
 11  MOCODES       853380 non-null   object
 12  VICT_AGE      1005104 non-null  int64
 13  VICT_SEX      860353 non-null   object
 14  PREMIS_CD     1005104 non-null  int32
 15  PREMIS_DESC   1004516 non-null  object
 16  WEAPON_DESC   327244 non-null   object
 17  STATUS_DESC   1005104 non-null  object
 18  CRM_CD_1      1005104 non-null  int32
 19  CRM_CD_2      1005104 non-null  int32
 20  CRM_CD_3      1005104 non-null  int32
 21  CRM_CD_4      1005104 non-null  int32
 22  LOCATION      1005104 non-null  object
 23  CROSS_STREET  154237 non-null   object
 24  LAT           1005104 non-null  float64
 25  LON           1005104 non-null  float64
dtypes: float64(2), int32(5), int64(8), object(11)
memory usage: 180.2+ MB

In [ ]:
crime_data_reformat = crime_data_rename.copy()

In [ ]:
# Remove tab from text fields
text_field_w_tab = ["LOCATION", "CROSS_STREET"]
for field in text_field_w_tab:
    crime_data_reformat[field] = crime_data_reformat[field].str.replace("\t", " ")
    crime_data_reformat[field] = crime_data_reformat[field].str.strip()

### 7. *Save new data.*

In [ ]:
# Save data
file_name = "./data/data-clean-pandas.csv"
crime_data_clean = crime_data_reformat.copy()
crime_data_clean.drop(columns= ["index"], inplace= True)
crime_data_clean.to_csv(file_name, index= False)

# Read & view cleaned data
crime_data_clean = pan.read_csv(file_name)
crime_data_clean

,DR_NO,DATE_RPTD,DATE_OCC,TIME_OCC,AREA,AREA_NAME,RPT_DIST_NO,PART_1_2,CRM_CD,CRM_CD_DESC,...,WEAPON_DESC,STATUS_DESC,CRM_CD_1,CRM_CD_2,CRM_CD_3,CRM_CD_4,LOCATION,CROSS_STREET,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,WILSHIRE,784,1,510,VEHICLE - STOLEN,...,NaN,ADULT ARREST,510,998,0,0,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,CENTRAL,182,1,330,BURGLARY FROM VEHICLE,...,NaN,INVEST CONT,330,998,0,0,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,SOUTHWEST,356,1,480,BIKE - STOLEN,...,NaN,INVEST CONT,480,0,0,0,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,VAN NUYS,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,NaN,INVEST CONT,343,0,0,0,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,HOLLENBECK,413,1,510,VEHICLE - STOLEN,...,NaN,INVEST CONT,510,0,0,0,200 E AVENUE 28,NaN,34.0820,-118.2130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005099,250304184,02/18/2025 12:00:00 AM,02/14/2025 12:00:00 AM,1200,3,SOUTHWEST,328,1,510,VEHICLE - STOLEN,...,NaN,INVEST CONT,510,0,0,0,700 W 28TH ST,NaN,34.0270,-118.2794
1005100,252104053,01/19/2025 12:00:00 AM,01/17/2025 12:00:00 AM,1530,21,TOPANGA,2114,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,NaN,INVEST CONT,341,0,0,0,22200 ELKWOOD ST,NaN,34.2128,-118.6103
1005101,250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,SOUTHWEST,358,1,510,VEHICLE - STOLEN,...,NaN,INVEST CONT,510,0,0,0,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895
1005102,250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,SOUTHWEST,325,1,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",...,NaN,INVEST CONT,522,0,0,0,2600 ELLENDALE PL,NaN,34.0307,-118.2923
1005103,250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,HARBOR,509,1,210,ROBBERY,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",INVEST CONT,210,0,0,0,24300 WESTERN AV,NaN,33.8046,-118.3074